USE  ProjectBase;
go


CREATE  TABLE  SHOP_PRODUCTS
(
    ID INTEGER PRIMARY KEY  IDENTITY,
    PRODUCT_NAME VARCHAR(125),
    PRODUCT_PRICE FLOAT,
    PRODUCT_DESC VARCHAR(255),
    PRODUCT_LOG_DATE DATETIME,
    PRODUCT_STOCK_AMOUNT INTEGER
);
GO

INSERT INTO SHOP_PRODUCTS(PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DESC, PRODUCT_LOG_DATE, PRODUCT_STOCK_AMOUNT)
 VALUES ('Alata Soup',23.4,'Organic Natural Soup',SYSDATETIME() ,200) ;
GO
ALTER TABLE  SHOP_PRODUCTS
DROP COLUMN  PRODUCT_PRICE;