CREATE DATABASE AUTH;


 USE AUTH;



CREATE TABLE USER_DATA(
    USER_ID VARCHAR(255) PRIMARY KEY ,
  USER_NAME VARCHAR(255),
  USER_PASSWORD VARCHAR(255),
  USER_PIC_PATH  VARCHAR(255),
  USER_DES VARCHAR(255),
  DATE_ACCOUNT DATETIME DEFAULT NOW()
);
# INSERT INTO USER_DATA(USER_ID, USER_NAME, USER_PASSWORD, USER_PIC_PATH, USER_DES) VALUES ()
drop table USER_DATA;

# CREATE TABLE PICHANDLEDB