
DROP TABLE IF EXISTS GRID_BLOG_ADMIN;
CREATE DATABASE  BLOGDB;

CREATE  TABLE  blogdb.GRID_BLOG_ADMIN(
 BLOG_ADMIN_USERNAME varchar(255),
 BLOG_ADMIN_FULL_NAME varchar(255),
 BLOG_ADMIN_DATE_OF_BIRTH DATE,
 BLOG_ADMIN_IMAGE_DATA BYTEA,
 BLOG_ADMIN_IMAGE_TYPE varchar(5)
);


DROP TABLE IF EXISTS GRID_BLOG_ADMIN;

CREATE TABLE blogdb.GRID_BLOG_ARTICLES(
    ARTICLE_ID INTEGER PRIMARY KEY ,
    ARTICLE_TITLE varchar(12),
    ARTICLE_HEADER_IMAGE BYTEA ,
    ARTICLE_META_DATA varchar(100) ,
    ARTICLE_CREATION_DATE DATE ,
    ARTICLE_DATA_PARA1 TEXT,
    ARTICLE_DATA_PARA1_IMAGE BYTEA,
    ARTICLE_DATA_PARA2 TEXT,
    ARTICLE_DATA_PARA2_IMAGE BYTEA,
    ARTICLE_DATA_PARA3 TEXT,
    ARTICLE_DATA_PARA3_IMAGE BYTEA
);

DROP TABLE IF EXISTS GRID_BLOG_ADMIN;
CREATE TABLE blogdb.GRID_BLOG_READERS(
BLOG_READER_ID  INTEGER PRIMARY KEY ,
BLOG_READER_USERNAME  varchar(50),
BLOG_READER_EMAIL varchar(28)
);
