-- CREATING  ACCOUNT TABLE FOR  BLOG USERS
CREATE DATABASE
  SavinateBlogDB;

USE
  SavinateBlogDB;

DROP TABLE
  IF EXISTS BLOG_USER;


-- FOR PEOPLE TO POST BLOG ON THE SITE
CREATE TABLE
  BLOG_USER(
    USER_ID VARCHAR(64) PRIMARY KEY NOT NULL,
    USER_FIRST_NAME VARCHAR(20) NOT NULL,
    USER_LAST_NAME VARCHAR(20) NOT NULL,
    USER_OTHER_NAME VARCHAR(20) NOT NULL,
    USER_USERNAME VARCHAR(20) NOT NULL,
    USER_PASSWORD VARCHAR(100) NOT NULL,
    USER_IMAGE VARCHAR(12000),
    USER_IMAGE_TYPE VARCHAR(6),
    USER_DESCRIP VARCHAR(400),
    USER_EMAIL VARCHAR(20),
    USER_TELEPHONE VARCHAR(20),
    USER_DATE_REG DATETIME DEFAULT NOW()
  );


drop table BLOG_USER;
drop schema savinateblogdb;
# INSERT INTO BLOG_USER(USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_OTHER_NAME, USER_USERNAME, USER_PASSWORD, USER_IMAGE, USER_DESCRIP, USER_EMAIL, USER_TELEPHONE)
#  VALUES ('23','Obed',);


select USER_IMAGE FROM BLOG_USER
where USER_FIRST_NAME ='sdsdsdsd';


-- FOR  BLOG  POST ON THE SITE
CREATE TABLE BLOG_INFO(
    USER_ID VARCHAR(64),
    ARTICLE_ID VARCHAR(255),
    ARTICLE_NAME VARCHAR(255),
    ARTICLE_DATE DATETIME DEFAULT  NOW(),
    ARTICLE_META VARCHAR(255),
    ARTICLE_IMAGE1 LONGBLOB,
    ARTICLE_IMAGE2 LONGBLOB,
    ARTICLE_IMAGE3 LONGBLOB,
    ARTICLE_PARA1 LONGTEXT,
    ARTICLE_PARA2 LONGTEXT,
    ARTICLE_PARA3 LONGTEXT

);
#
DROP TABLE BLOG_INFO