CREATE
    DATABASE RAFTERSDB;


USE
    RAFTERSDB;

-- TABLE FOR  MAIN ACCOUNT
CREATE
    TABLE MAIN_ACCOUNT
(
        USER_ID VARCHAR(450),
    USERNAME        VARCHAR(255) ,
    USER_IMAGE      LONGBLOB,
   USER_IMAGE_FORMAT   VARCHAR(6),
    USER_FIRST_NAME VARCHAR(255) ,
    USER_LAST_NAME  VARCHAR(255) ,
    USER_PASSWORD   VARCHAR(255) ,
    USER_LOG_DATE   DATETIME DEFAULT NOW()
);
# SELECT USER_IMAGE , use FROM MAIN_ACCOUNT WHERE USER_ID = '';

SELECT USERNAME ,USER_PASSWORD FROM MAIN_ACCOUNT WHERE USERNAME='Gridlaw';


INSERT INTO MAIN_ACCOUNT(USER_ID, USERNAME, USER_IMAGE, USER_FIRST_NAME, USER_LAST_NAME, USER_PASSWORD) VALUES ()

DROP TABLE
  IF EXISTS MAIN_ACCOUNT;
-- TABLE FOR  CLIENT ACCOUNT

CREATE
    TABLE CUSTOMER_DB
(
    CLIENT_ID    VARCHAR(455) ,
    CLIENT_JOB_NAME        VARCHAR(255),
    CLIENT_FULL_NAME VARCHAR(255) ,
    CLIENT_JOB_DES  VARCHAR(400) ,
    CLIENT_EMAIL   VARCHAR(255) ,
    CLIENT_PHONE   VARCHAR(255) ,
    CLIENT_WHATSAPP   VARCHAR(255) ,
    CLIENT_JOB_DATE  DATETIME ,
    CLIENT_JOB_IMG  LONGBLOB,
    CLIENT_JOB_IMG_FORMAT  VARCHAR(7),
    POSTED_DATE   DATETIME DEFAULT NOW()
);
INSERT INTO CUSTOMER_DB(CLIENT_ID, CLIENT_JOB_NAME, CLIENT_FULL_NAME, CLIENT_JOB_DES, CLIENT_EMAIL, CLIENT_PHONE, CLIENT_WHATSAPP, CLIENT_JOB_DATE, CLIENT_JOB_IMG, CLIENT_JOB_IMG_FORMAT)
VALUES ()
DROP TABLE
  IF EXISTS CUSTOMER_DB;
SELECT CLIENT_JOB_NAME ,  CLIENT_JOB_DES , CLIENT_FULL_NAME ,CLIENT_EMAIL, CLIENT_PHONE, CLIENT_WHATSAPP ,POSTED_DATE ,CLIENT_JOB_DATE
FROM customer_db;