
CREATE DATABASE JOB_BOARD_DATABASE;

USE JOB_BOARD_DATABASE;

CREATE TABLE IF NOT EXISTS COMPANY_ACCOUNTS(
  COMPANY_ID VARCHAR(255) PRIMARY KEY NOT NULL,
  COMPANY_NAME VARCHAR(160) NOT NULL,
  COMPANY_EMAIL VARCHAR(160) NOT NULL,
  COMPANY_TELEPHONE VARCHAR(160) NOT NULL ,
  COMPANY_IMG  LONGBLOB,
  COMPANY_DESC VARCHAR(255) NOT NULL ,
  COMPANY_USERNAME VARCHAR(30) NOT NULL,
  COMPANY_PASSWORD VARCHAR(30) NOT NULL ,
  COMPANY_JOB_MAIL VARCHAR(40),
  COMPANY_REG_DATE DATETIME DEFAULT NOW()
);

 DROP TABLE  JOBS_DATA ;

CREATE TABLE  IF NOT EXISTS JOBS_DATA(
  JOB_ID VARCHAR(255) PRIMARY KEY  NOT NULL,
  JOB_TITLE VARCHAR(40) NOT NULL,
  JOB_DESC VARCHAR(60) NOT NULL,
  JOB_TYPE ENUM('Technology','Building-Construction','Health-Care','Finance-Money','Secretary','Hospitality'),
  COMPANY_POSTED_ID VARCHAR(255) NOT NULL ,
  JOB_POSTED_DATE DATETIME DEFAULT  NOW(),
FOREIGN KEY JOB_DATA_TO_COMPANY_ID(COMPANY_POSTED_ID) REFERENCES COMPANY_ACCOUNTS(COMPANY_ID)
);

SELECT JOB_POSTED_DATE DATETIME DEFAULT CURRENT_DATE() ,
SELECT  CURRENT_DATE();