CREATE  DATABASE  HAIR_SALON;
GO
USE  HAIR_SALON;
go


CREATE  TABLE  HAIR_SALON
(
    ID INTEGER PRIMARY KEY  IDENTITY,
    CUSTOMER_NAME VARCHAR(125),
    CUSTOMER_HAIR_DESC VARCHAR(100),
    CUSTOMER_HAIR_PRICE INTEGER,
    CUSTOMER_LOG_DATE DATETIME,
);
GO

CREATE TABLE CUSTOMERS
(
    customerId  varchar(255)  PRIMARY KEY ,
    customerName  varchar(255),
     customerLocation   varchar(255),
     customerTelephone  varchar(255),
)
go


INSERT INTO HAIR_SALON(CUSTOMER_NAME, CUSTOMER_HAIR_DESC, CUSTOMER_HAIR_PRICE, CUSTOMER_LOG_DATE)
 VALUES ('Akosua','Wiggle Hair Style',23,sysdatetime()) ;
GO

DROP TABLE  CUSTOMERS;
