
CREATE DATABASE SCHOOL_ASSEMENT;
GO

DROP DATABASE IF EXISTS SCHOOL_ASSEMENT;
GO

USE SCHOOL_ASSEMENT;
GO

DROP TABLE IF EXISTS  STUDENT_DATA;
GO

CREATE TABLE STUDENT_DATA(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_FULLNAME VARCHAR(255),
STUDENT_DOB DATE,
STUDENT_LOCATION VARCHAR(255),
STUDENT_AGE VARCHAR(255),
STUDENT_SUBJECT VARCHAR(255),
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255),
STUDENT_TOTAL_MARKS DECIMAL,
STUDENT_DATE_ADDED DATETIME
);
go

SELECT * FROM STUDENT_DATA;