-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE GET_SUBJECT_DATA1
	-- Add the parameters for the stored procedure here
	(@STUDENT_SUBJECT VARCHAR(255))
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	IF @STUDENT_SUBJECT = 'MATHEMATICS'
		BEGIN
	 
		--SELECT 	STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		--RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		--FROM dbo.STUDENT_DATA_MATHS

		SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_MATHS
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID = STUDENT_DATA_MATHS.STUDENT_ID 

	END

	IF @STUDENT_SUBJECT = 'SCIENCE'
		BEGIN
	
	SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_SCI
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID = STUDENT_DATA_SCI.STUDENT_ID
		 


	END

IF @STUDENT_SUBJECT = 'ENGLISH'
		BEGIN
		
SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_ENG
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_ENG.STUDENT_ID
		



	END

	IF @STUDENT_SUBJECT = 'ICT'
		BEGIN
	SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_ICT
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_ICT.STUDENT_ID
		
		
		

	END

	IF @STUDENT_SUBJECT = 'GHANAIAN LANG'
		BEGIN
	
		SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_GHAINLANG
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_GHAINLANG.STUDENT_ID;

	END

	IF @STUDENT_SUBJECT = 'FRENCH'
		BEGIN
	SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_FRENCH
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_FRENCH.STUDENT_ID;
		
		
		


	END

	IF @STUDENT_SUBJECT = 'RME'
		BEGIN
	SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_RME
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_RME.STUDENT_ID
		

	END

	IF @STUDENT_SUBJECT = 'HISTORY'
		BEGIN
	SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_HISTORY
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_HISTORY.STUDENT_ID
	
	

	END

	IF @STUDENT_SUBJECT = 'CREATIVE ART'
		BEGIN
	
		SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_CREATIVEART
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_CREATIVEART.STUDENT_ID
		
		

	END

	IF @STUDENT_SUBJECT = 'OURWORLD'
		BEGIN
	
		SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_OURWORLD
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_OURWORLD.STUDENT_ID


	END

	IF @STUDENT_SUBJECT = 'PROJECT WORKS'
		BEGIN
	
		SELECT STUDENT_INFO.STUDENT_ID ,STUDENT_INFO.STUDENT_FULLNAME,STUDENT_30PERCENT ,STUDENT_70PERCENT,STUDENT_TOTAL_MARKS ,STUDENT_REMARKS, STUDENT_GRADE,
		RANK () OVER (ORDER BY STUDENT_TOTAL_MARKS DESC ) AS STUDENTS_POSITION 
		FROM dbo.STUDENT_DATA_PROJECTWORK
		INNER JOIN STUDENT_INFO 
		ON STUDENT_INFO.STUDENT_ID =STUDENT_DATA_PROJECTWORK.STUDENT_ID
		
		

	END
END
GO
