
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		
-- Create date: 
-- Description:	
-- =============================================
CREATE PROCEDURE dbo.STORE_STUDENT_MARKS
	(@STUDENT_SUBJECT VARCHAR(255) , 
	@STUDENT_ID INT,
	@STUDENT_70PERCENT FLOAT,
	@STUDENT_30PERCENT FLOAT,
	@STUDENT_TOTAL_MARKS FLOAT,
	@STUDENT_REMARKS VARCHAR(255),
	@STUDENT_GRADE VARCHAR(255))
	-- Add the parameters for the stored procedure here
	
AS

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	IF @STUDENT_SUBJECT = 'MATHEMATICS'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_MATHS(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS,@STUDENT_REMARKS ,@STUDENT_GRADE )


	END

	IF @STUDENT_SUBJECT = 'SCIENCE'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_SCI(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )


	END

	IF @STUDENT_SUBJECT = 'ENGLISH'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_ENG(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )


	END

	IF @STUDENT_SUBJECT = 'ICT'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_ICT(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )


	END

	IF @STUDENT_SUBJECT = 'GHANAIAN LANG'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_GHAINLANG(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )


	END

	IF @STUDENT_SUBJECT = 'FRENCH'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_FRENCH(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )


	END

	IF @STUDENT_SUBJECT = 'RME'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_RME(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )
	END

	IF @STUDENT_SUBJECT = 'HISTORY'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_HISTORY(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )

	END

	IF @STUDENT_SUBJECT = 'CREATIVE ART'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_CREATIVEART(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )

	END

	IF @STUDENT_SUBJECT = 'OUR WORLD'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_OURWORLD(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )

	END

	IF @STUDENT_SUBJECT = 'PROJECT WORKS'
		BEGIN
	INSERT INTO dbo.STUDENT_DATA_PROJECTWORK(STUDENT_ID,
	STUDENT_70PERCENT ,
	STUDENT_30PERCENT,
	STUDENT_TOTAL_MARKS,
	STUDENT_REMARKS ,
	STUDENT_GRADE)
	VALUES(@STUDENT_ID ,@STUDENT_70PERCENT,@STUDENT_30PERCENT,@STUDENT_TOTAL_MARKS ,@STUDENT_REMARKS ,@STUDENT_GRADE )

	END

END
GO
