
CREATE DATABASE SCHOOL_ASSEMENT;
GO

DROP DATABASE IF EXISTS SCHOOL_ASSEMENT;
GO

USE SCHOOL_ASSEMENT;
GO

DROP TABLE IF EXISTS STUDENT_DATA_GHAINLANG,STUDENT_DATA_OURWORLD,STUDENT_DATA_PROJECTWORK,
STUDENT_DATA_FRENCH,STUDENT_DATA_RME,STUDENT_DATA_HISTORY,STUDENT_DATA_CREATIVEART;
GO

CREATE TABLE STUDENT_INFO(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_FULLNAME VARCHAR(255),
STUDENT_CLASS VARCHAR(255),
STUDENT_DOB DATE,
STUDENT_LOCATION VARCHAR(255),
STUDENT_AGE VARCHAR(255),
STUDENT_DATE_ADDED DATETIME
);
GO

SELECT * FROM STUDENT_DATA_MATHS;
GO


CREATE TABLE STUDENT_DATA_MATHS(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
)
GO



CREATE TABLE STUDENT_DATA_ENG(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO

CREATE TABLE STUDENT_DATA_SCI(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO

CREATE TABLE STUDENT_DATA_ICT(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO

CREATE TABLE STUDENT_DATA_GHAINLANG(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO

CREATE TABLE STUDENT_DATA_FRENCH(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO

CREATE TABLE STUDENT_DATA_RME(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
)
GO
CREATE TABLE STUDENT_DATA_HISTORY(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO

CREATE TABLE STUDENT_DATA_CREATIVEART(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO
CREATE TABLE STUDENT_DATA_OURWORLD(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO
CREATE TABLE STUDENT_DATA_PROJECTWORK(
STUDENT_ID  INT PRIMARY KEY,
STUDENT_30PERCENT FLOAT,
STUDENT_70PERCENT FLOAT,
STUDENT_TOTAL_MARKS FLOAT,
STUDENT_REMARKS VARCHAR(255),
STUDENT_GRADE VARCHAR(255)
);
GO


